config/routes.rb
Rufio::Application.routes.draw do
  resources :environments
  resources :events
  resources :settings, only: :index
  root :to => 'environments#index'

  mount OpenSesame::Engine => OpenSesame.mount_prefix
end

app/models/environment.rb
class Environment < ActiveRecord::Base
  attr_accessible :name, :token
  after_create :generate_token

  has_many :events

  def to_param
    "#{id}-#{name.parameterize}"
  end

  def path
    Rails.application.routes.url_helpers.environment_path(self)
  end

  private

  def generate_token
    self.update_attributes(token: SecureRandom.hex(16)) if token.blank?
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :campaign_id, :campaign_name, :customer_id, :email_address, :email_id, :event_id, :event_type, :subject, :timestamp, :environment_id

  belongs_to :environment

  default_scope order('created_at DESC')
  scope :errors, where(event_type: :email_bounced)

  self.per_page = 100
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :find_environments

  private

  def find_environments
    @environments = Environment.all
  end
end

app/controllers/environments_controller.rb
class EnvironmentsController < ApplicationController
  before_filter :authenticate_opensesame!

  # GET /environments
  # GET /environments.json
  def index
    if @environments.any?
      redirect_to @environments.first
    else
      redirect_to settings_path
    end
  end

  # GET /environments/1
  # GET /environments/1.json
  def show
    @environment = Environment.find(params[:id])
    @filters = Event.group(:event_type).count

    if params[:filter]
      @filter = params[:filter]
      @events = @environment.events.where(event_type: @filter).paginate(page: params[:page])
    else
      @events = @environment.events.paginate(page: params[:page])
    end

    render "events/index"
  end

  # GET /environments/new
  # GET /environments/new.json
  def new
    @environment = Environment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @environment }
    end
  end

  # GET /environments/1/edit
  def edit
    @environment = Environment.find(params[:id])
  end

  # POST /environments
  # POST /environments.json
  def create
    @environment = Environment.new(params[:environment])

    respond_to do |format|
      if @environment.save
        format.html { redirect_to @environment, notice: 'Environment was successfully created.' }
        format.json { render json: @environment, status: :created, location: @environment }
      else
        format.html { render action: "new" }
        format.json { render json: @environment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /environments/1
  # PUT /environments/1.json
  def update
    @environment = Environment.find(params[:id])

    respond_to do |format|
      if @environment.update_attributes(params[:environment])
        format.html { redirect_to @environment, notice: 'Environment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @environment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /environments/1
  # DELETE /environments/1.json
  def destroy
    @environment = Environment.find(params[:id])
    @environment.destroy

    respond_to do |format|
      format.html { redirect_to environments_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :authenticate_opensesame!, except: :create
  before_filter :find_environment, only: :create

  # GET /events
  # GET /events.json
  def index
    @events = Event.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    if @environment
      attributes = params.delete(:data)
      attributes[:timestamp] = params[:event].delete(:timestamp).to_s
      attributes[:environment_id] = @environment.id
      attributes.merge!(params[:event])
      p attributes

      @event = Event.new(attributes)

      respond_to do |format|
        if @event.save
          format.html { redirect_to @event, notice: 'Event was successfully created.' }
          format.json { render json: @event, status: :created, location: @event }
        else
          format.html { render action: "new" }
          format.json { render json: @event.errors, status: :unprocessable_entity }
        end
      end
    else
      render nothing: true
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  private

  def find_environment
    @environment = Environment.find_by_token(params[:token])
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/environments_helper.rb
module EnvironmentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/application/_footer.html.erb
<div id="footer">
  <%= link_to "Settings", settings_path %>
</div>

app/views/application/_header.html.erb
<div id="header">
  <h1><%= link_to "Rufio", root_path %></h1>

  <div class="right">
    <%= render 'filters' if @filters %>
    <%= render 'select_environment' if @environment && !@environment.new_record? %>
  </div>
</div>

app/views/environments/_filters.html.erb
<span id="filters">
  <% @filters.each do |filter_name, count| %>
    <% if filter_name == @filter %>
      <%= filter_name %>
    <% else %>
      <%= link_to filter_name, environment_path(@environment, filter: filter_name) %>
    <% end %>
    (<%= count %>)
  <% end %>

  <%= link_to "reset", @environment if @filter %>
</span>

app/views/environments/_form.html.erb
<%= form_for(@environment) do |f| %>
  <% if @environment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@environment.errors.count, "error") %> prohibited this environment from being saved:</h2>

      <ul>
      <% @environment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/environments/_select_environment.html.erb
<% options = options_from_collection_for_select(@environments, 'path', 'name', @environment.path) %>
<%= select(:environment, :id, options) %>

app/views/environments/edit.html.erb
<h1>Editing environment</h1>

<%= render 'form' %>

<p>
  Hook Customer.io up to <b><%= "http://#{request.host}/events.json?token=#{@environment.token}" %></b>
</p>

<%= link_to 'Show', @environment %> |
<%= link_to 'Back', settings_path %>

app/views/environments/index.html.erb
<ul>
  <% @environments.each do |environment| %>
    <li><%= link_to environment.name, environment %></li>
  <% end %>
</ul>

<%= link_to 'New Environment', new_environment_path %>

app/views/environments/new.html.erb
<h1>New environment</h1>

<%= render 'form' %>

<%= link_to 'Back', environments_path %>

app/views/events/_customer_unsubscribed.html.erb
<%= event.email_address %>
unsubscribed
(<%= time_ago_in_words(Time.at(event.timestamp.to_i)) %> ago)

app/views/events/_email_bounced.html.erb
The <%= event.campaign_name %> email
(<i><%= event.subject %></i>)
for
<%= event.email_address %>
<%= link_to 'bounced', event %>
(<%= time_ago_in_words(Time.at(event.timestamp.to_i)) %> ago)

app/views/events/_email_clicked.html.erb
<%= event.email_address %>
<%= link_to 'clicked', event %>
in the <%= event.campaign_name %> email:
<i><%= event.subject %></i>
(<%= time_ago_in_words(Time.at(event.timestamp.to_i)) %> ago)

app/views/events/_email_delivered.html.erb
<%= event.email_address %>
<%= link_to 'received', event %>
the <%= event.campaign_name %> email:
<i><%= event.subject %></i>
(<%= time_ago_in_words(Time.at(event.timestamp.to_i)) %> ago)

app/views/events/_email_drafted.html.erb
<%= link_to 'New draft email', event %>:
<%= event.campaign_name %>
(<i><%= event.subject %></i>)
for
<%= event.email_address %>
(<%= time_ago_in_words(Time.at(event.timestamp.to_i)) %> ago)

app/views/events/_email_dropped.html.erb
<%= link_to 'Email dropped', event %>:
<%= event.campaign_name %>
(<i><%= event.subject %></i>)
for
<%= event.email_address %>
(<%= time_ago_in_words(Time.at(event.timestamp.to_i)) %> ago)

app/views/events/_email_opened.html.erb
<%= event.email_address %>
<%= link_to 'opened', event %>
the <%= event.campaign_name %> email:
<i><%= event.subject %></i>
(<%= time_ago_in_words(Time.at(event.timestamp.to_i)) %> ago)

app/views/events/_email_spammed.html.erb
<%= event.email_address %>
<%= link_to 'marked as spam', event %>
the <%= event.campaign_name %> email:
<i><%= event.subject %></i>
(<%= time_ago_in_words(Time.at(event.timestamp.to_i)) %> ago)

app/views/events/_event.html.erb
<%= div_for event, class: event.event_type do %>
  <%= render "events/#{event.event_type}", event: event %>
<% end %>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :event_type %><br />
    <%= f.text_field :event_type %>
  </div>
  <div class="field">
    <%= f.label :event_id %><br />
    <%= f.text_field :event_id %>
  </div>
  <div class="field">
    <%= f.label :timestamp %><br />
    <%= f.text_field :timestamp %>
  </div>
  <div class="field">
    <%= f.label :customer_id %><br />
    <%= f.text_field :customer_id %>
  </div>
  <div class="field">
    <%= f.label :email_address %><br />
    <%= f.text_field :email_address %>
  </div>
  <div class="field">
    <%= f.label :email_id %><br />
    <%= f.text_field :email_id %>
  </div>
  <div class="field">
    <%= f.label :subject %><br />
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :campaign_id %><br />
    <%= f.text_field :campaign_id %>
  </div>
  <div class="field">
    <%= f.label :campaign_name %><br />
    <%= f.text_field :campaign_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Destroy', @event, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', @event.environment %>

app/views/events/index.html.erb
<% @events.each do |event| %>
  <%= div_for event, class: event.event_type, data: { customerid: event.customer_id } do %>
    <%= render "events/#{event.event_type}", event: event %>
  <% end %>
<% end %>

<div id="pagination">
  <div><%= page_entries_info @events %></div>
  <%= will_paginate @events %>
</div>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Event type:</b>
  <%= @event.event_type %>
</p>

<p>
  <b>Event:</b>
  <%= @event.event_id %>
</p>

<p>
  <b>Timestamp:</b>
  <%= @event.timestamp %>
</p>

<p>
  <b>Customer:</b>
  <%= @event.customer_id %>
</p>

<p>
  <b>Email address:</b>
  <%= @event.email_address %>
</p>

<p>
  <b>Email:</b>
  <%= @event.email_id %>
</p>

<p>
  <b>Subject:</b>
  <%= @event.subject %>
</p>

<p>
  <b>Campaign:</b>
  <%= @event.campaign_id %>
</p>

<p>
  <b>Campaign name:</b>
  <%= @event.campaign_name %>
</p>


<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', @event.environment %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rufio</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "header" %>
<%= yield %>
<%= render "footer" %>

</body>
</html>

app/views/settings/index.html.erb
<ul>
  <% @environments.each do |environment| %>
    <li><%= link_to environment.name, edit_environment_path(environment) %></li>
  <% end %>
</ul>

<%= link_to 'New Environment', new_environment_path %>